#!/usr/bin/env bash
# V.A.N.T.i.S. Audit Log Compiler
# Stop command hook — compiles the session ledger into a structured audit log, zero model tokens.
#
# Triggered by: agent Stop hook (end of every session)
# Reads:  .gemini/tmp/session-ledger.jsonl
# Writes: logs/YYYY-MM-DD/YYYY-MM-DD_HHMMSS_AutoLog_Session-Audit.md
# Clears: .gemini/tmp/session-ledger.jsonl on success

# Consume stdin to prevent script hanging
cat > /dev/null

LEDGER=".gemini/tmp/session-ledger.jsonl"

# Exit silently if no ledger or ledger is empty — nothing happened this session
if [ ! -f "$LEDGER" ] || [ ! -s "$LEDGER" ]; then
  exit 0
fi

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H%M%S)
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
LOG_DIR="logs/$DATE"
LOG_FILE="$LOG_DIR/${DATE}_${TIME}_AutoLog_Session-Audit.md"

mkdir -p "$LOG_DIR"

# --- Build file list from ledger ---
if command -v jq >/dev/null 2>&1; then
  FILES_MODIFIED=$(jq -r '.file' "$LEDGER" | sort -u)
  FIRST_TS=$(head -1 "$LEDGER" | jq -r '.timestamp')
  LAST_TS=$(tail -1 "$LEDGER" | jq -r '.timestamp')
  ENTRY_COUNT=$(wc -l < "$LEDGER" | tr -d ' ')
  FILE_COUNT=$(jq -r '.file' "$LEDGER" | sort -u | wc -l | tr -d ' ')
  AGENT_NAME=$(jq -r '.agent // empty' "$LEDGER" | grep -v '^$' | head -1)
else
  FILES_MODIFIED=$(grep -o '"file":"[^"]*"' "$LEDGER" | sed 's/"file":"//;s/"//' | sort -u)
  FIRST_TS=$(head -1 "$LEDGER" | grep -o '"timestamp":"[^"]*"' | sed 's/"timestamp":"//;s/"//')
  LAST_TS=$(tail -1 "$LEDGER" | grep -o '"timestamp":"[^"]*"' | sed 's/"timestamp":"//;s/"//')
  ENTRY_COUNT=$(wc -l < "$LEDGER" | tr -d ' ')
  FILE_COUNT=$(echo "$FILES_MODIFIED" | grep -c .)
  AGENT_NAME=$(grep -o '"agent":"[^"]*"' "$LEDGER" | head -1 | sed 's/"agent":"//;s/"//')
fi

if [ -z "$AGENT_NAME" ]; then
  AGENT_NAME="Unknown Agent"
fi

FILES_LIST=$(echo "$FILES_MODIFIED" | sed 's/^/- /')

# --- Git context ---
GIT_STAT=$(git diff --stat HEAD 2>/dev/null)
if [ -z "$GIT_STAT" ]; then
  GIT_STAT="No uncommitted changes at session end."
fi

LAST_COMMIT=$(git log -1 --pretty=format:"%h — %s" 2>/dev/null || echo "No commits yet")

# --- Write the log ---
cat > "$LOG_FILE" <<EOF
# Auto-Audit Log: Session $DATE
Agent: $AGENT_NAME (Execution Plane) — Automated
Branch: $BRANCH
Session Start: $FIRST_TS
Session End: $LAST_TS
Tool Invocations: $ENTRY_COUNT
Unique Files Touched: $FILE_COUNT
Generated By: compile-audit-log.sh (tokenless)

---

## Files Modified This Session

$FILES_LIST

---

## Git State at Session End

**Last Commit:** $LAST_COMMIT

\`\`\`
$GIT_STAT
\`\`\`

---

## Raw Ledger

\`\`\`jsonl
$(cat "$LEDGER")
\`\`\`

---
*Auto-generated | Zero model tokens consumed | V.A.N.T.i.S. Tokenless Audit Engine v1.1*
EOF

# Clear the ledger after successful compilation
rm -f "$LEDGER"

echo "[AutoLog] Audit log written: $LOG_FILE ($FILE_COUNT files, $ENTRY_COUNT tool calls)"
