#!/usr/bin/env bash
# V.A.N.T.i.S. Pre-Compact Snapshot Hook
# PreCompact command hook — captures the agent's context and working state before summarization.
#
# Triggered by: Claude Code PreCompact hook (mid-session)
# Reads:  02_MACHINE/State/session-state_LATEST.md
#         .gemini/tmp/session-ledger.jsonl
#         stdin (Conversation context history provided by Claude)
# Writes: 02_MACHINE/State/precompact-snapshot_YYYY-MM-DD_HHMMSS.md

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H%M%S)
SNAPSHOT_DIR="02_MACHINE/State"
SNAPSHOT_FILE="$SNAPSHOT_DIR/precompact-snapshot_${DATE}_${TIME}.md"
LEDGER=".gemini/tmp/session-ledger.jsonl"
STATE_LATEST="02_MACHINE/State/session-state_LATEST.md"

git_safe() {
  git -c core.fsmonitor=false "$@" 2>/dev/null
}

mkdir -p "$SNAPSHOT_DIR"

# --- Write the snapshot ---
cat > "$SNAPSHOT_FILE" <<EOF
# Pre-Compact Snapshot: $DATE $TIME
Agent: Claude (Execution Plane) — Automated
Branch: $(git_safe branch --show-current || echo "unknown")
Type: Pre-Compact Context Save
Generated By: precompact-snapshot.sh

---

## Current Objective & State
*(From 02_MACHINE/State/session-state_LATEST.md)*

$(if [ -f "$STATE_LATEST" ]; then cat "$STATE_LATEST"; else echo "No session-state_LATEST.md found."; fi)

---

## Session Progress (Ledger)
*(From .gemini/tmp/session-ledger.jsonl)*

\`\`\`jsonl
$(if [ -f "$LEDGER" ]; then cat "$LEDGER"; else echo "No session-ledger.jsonl found."; fi)
\`\`\`

---

## Context History (Raw)
*(Captured from stdin)*

\`\`\`markdown
$(cat)
\`\`\`

---
*Auto-generated | Pre-Compact Snapshot | V.A.N.T.i.S. Session Persistence Engine*
EOF

echo "[Snapshot] Pre-compact state saved: $SNAPSHOT_FILE"
